# PUI 2017 HW 7-2
## Yuwen Chang (ywc249)

In [1]:
# import with py 2 and py 3 compatibility
try:
    import urllib2
    from urllib2 import HTTPError
    from urllib2 import urlopen
    from urllib import urlencode
    from StringIO import StringIO as io

except ImportError:
    import urllib
    from urllib.error import HTTPError
    from urllib.request import urlopen, Request
    from urllib.parse import urlencode
    from io import BytesIO as io

import ast
import pandas as pd

In [2]:
# set SQL source
SQL_SOURCE = 'https://ywc249.carto.com/api/v2/sql?q='

# define query function
def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urlencode({'format':format, 'q':query}).encode('utf-8')
    try:
        response = urlopen(source, data)
    except HTTPError as e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [3]:
# test function
test = '''
SELECT *
FROM citibike
'''

df = pd.read_csv(io(queryCartoDB(test)), sep=',')
df.head()

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994156,NaN,351,2015-02-01 20:36:00+00,2015-02-01 20:42:00+00,435,W 21 St & 6 Ave,40.741740,5960,462,W 22 St & 10 Ave,40.746920,-74.004519,19217,Subscriber,1965.0,1
1,NaN,-73.976049,NaN,643,2015-02-03 14:39:00+00,2015-02-03 14:50:00+00,167,E 39 St & 3 Ave,40.748901,9806,488,W 39 St & 9 Ave,40.756458,-73.993722,17575,Subscriber,1971.0,1
2,NaN,-73.979481,NaN,1379,2015-02-04 07:07:00+00,2015-02-04 07:30:00+00,332,Cherry St,40.712199,13113,440,E 45 St & 3 Ave,40.752554,-73.972826,20313,Subscriber,1973.0,1
3,NaN,-73.994811,NaN,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
4,NaN,-73.990093,NaN,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1

# Task 1

In [4]:
# Sort by start station ids
q = '''
SELECT *
FROM citibike
ORDER BY start_station_id
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.993929,NaN,359,2015-02-07 14:33:00+00,2015-02-07 14:39:00+00,72,W 52 St & 11 Ave,40.767272,42446,500,Broadway & W 51 St,40.762288,-73.983362,21114,Subscriber,1983.0,1
1,NaN,-73.993929,NaN,1678,2015-02-03 18:21:00+00,2015-02-03 18:49:00+00,72,W 52 St & 11 Ave,40.767272,11298,79,Franklin St & W Broadway,40.719116,-74.006667,21500,Subscriber,1964.0,1
2,NaN,-73.993929,NaN,1366,2015-02-04 18:40:00+00,2015-02-04 19:02:00+00,72,W 52 St & 11 Ave,40.767272,19501,476,E 31 St & 3 Ave,40.743943,-73.979661,20139,Subscriber,1971.0,1
3,NaN,-73.993929,NaN,574,2015-02-04 19:24:00+00,2015-02-04 19:33:00+00,72,W 52 St & 11 Ave,40.767272,20070,352,W 56 St & 6 Ave,40.763406,-73.977225,17997,Subscriber,1974.0,1
4,NaN,-73.993929,NaN,1944,2015-02-01 12:39:00+00,2015-02-01 13:12:00+00,72,W 52 St & 11 Ave,40.767272,1983,328,Watts St & Greenwich St,40.724055,-74.009660,17849,Customer,NaN,0
5,NaN,-73.993929,NaN,1537,2015-02-04 08:07:00+00,2015-02-04 08:33:00+00,72,W 52 St & 11 Ave,40.767272,13647,487,E 20 St & FDR Drive,40.733143,-73.975739,18900,Subscriber,1977.0,2
6,NaN,-73.993929,NaN,817,2015-02-05 09:01:00+00,2015-02-05 09:15:00+00,72,W 52 St & 11 Ave,40.767272,23938,267,Broadway & W 36 St,40.750977,-73.987654,16960,Subscriber,1980.0,2
7,NaN,-73.993929,NaN,2099,2015-02-03 10:28:00+00,2015-02-03 11:02:00+00,72,W 52 St & 11 Ave,40.767272,9054,328,Watts St & Greenwich St,40.724055,-74.009660,18653,Subscriber,1966.0,2
8,NaN,-73.993929,NaN,517,2015-02-04 08:18:00+00,2015-02-04 08:26:00+00,72,W 52 St & 11 Ave,40.767272,13797,520,W 52 St & 5 Ave,40.759923,-73.976485,14918,Subscriber,1977.0,1
9,NaN,-73.993929,NaN,455,2015-02-01 17:55:00+00,2015-02-01 18:03:00+00,72,W 52 St & 11 Ave,40.767272,5136,529,W 42 St & 8 Ave,40.757570,-73.990985,16427,Subscriber,1983.0,1
10,NaN,-73.993929,NaN,692,2015-02-04 08:38:00+00,2015-02-04 08:50:00+00,72,W 52 St & 11 Ave,40.767272,14063,520,W 52 St & 5 Ave,40.759923,-73.976485,20642,Subscriber,1975.0,1
11,NaN,-73.993929,NaN,838,2015-02-06 08:34:00+00,2015-02-06 08:48:00+00,72,W 52 St & 11 Ave,40.767272,32166,359,E 47 St & Park Ave,40.755103,-73.974987,21561,Subscriber,1984.0,2
12,NaN,-73.993929,NaN,345,2015-02-07 18:46:00+00,2015-02-07 18:51:00+00,72,W 52 St & 11 Ave,40.767272,44789,447,8 Ave & W 52 St,40.763707,-73.985162,17669,Subscriber,1983.0,1
13,NaN,-73.993929,NaN,386,2015-02-05 16:00:00+00,2015-02-05 16:06:00+00,72,W 52 St & 11 Ave,40.767272,27104,479,9 Ave & W 45 St,40.760193,-73.991255,15927,Subscriber,1973.0,1
14,NaN,-73.993929,NaN,928,2015-02-06 15:53:00+00,2015-02-06 16:08:00+00,72,W 52 St & 11 Ave,40.767272,35492,472,E 32 St & Park Ave,40.745712,-73.981948,18606,Subscriber,1972.0,1
15,NaN,-73.993929,NaN,659,2015-02-04 17:55:00+00,2015-02-04 18:06:00+00,72,W 52 St & 11 Ave,40.767272,18756,499,Broadway & W 60 St,40.769155,-73.981918,20592,Subscriber,1964.0,1
16,NaN,-73.993929,NaN,531,2015-02-05 09:27:00+00,2015-02-05 09:36:00+00,72,W 52 St & 11 Ave,40.767272,24327,510,W 51 St & 6 Ave,40.760660,-73.980420,17538,Subscriber,1972.0,2
17,NaN,-73.993929,NaN,915,2015-02-05 20:38:00+00,2015-02-05 20:53:00+00,72,W 52 St & 11 Ave,40.767272,30235,463,9 Ave & W 16 St,40.742065,-74.004432,15896,Subscriber,1984.0,1
18,NaN,-73.993929,NaN,388,2015-02-03 11:23:00+00,2015-02-03 11:30:00+00,72,W 52 St & 11 Ave,40.767272,9194,500,Broadway & W 51 St,40.762288,-73.983362,17196,Subscriber,1980.0,1
19,NaN,-73.993929,NaN,424,2015-02-05 08:42:00+00,2015-02-05 08:49:00+00,72,W 52 St & 11 Ave,40.767272,23547,2021,W 45 St & 8 Ave,40.759291,-73.988597,19390,Subscriber,1986.0,2
20,NaN,-73.993929,NaN,348,2015-02-03 13:01:00+00,2015-02-03 13:06:00+00,72,W 52 St & 11 Ave,40.767272,9494,478,11 Ave & W 41 St,40.760301,-73.998842,16754,Subscriber,1961.0,1
21,NaN,-73.993929,NaN,344,2015-02-01 09:49:00+00,2015-02-01 09:54:00+00,72,W 52 St & 11 Ave,40.767272,649,2021,W 45 St & 8 Ave,40.759291,-73.988597,14692,Subscriber,1986.0,2
22,NaN,-73.993929,NaN,552,2015-02-05 08:10:00+00,2015-02-05 08:19:00+00,72,W 52 St & 11 Ave,40.767272,22959,520,W 52 St & 5 Ave,40.759923,-73.976485,15927,Subscriber,1977.0,1
23,NaN,-73.993929,NaN,367,2015-02-04 08:59:00+00,2015-02-04 09:05:00+00,72,W 52 St & 11 Ave,40.767272,14395,500,Broadway & W 51 St,40.762288,-73.983362,18620,Subscriber,1981.0,1
24,NaN,-73.993929,NaN,301,2015-02-01 13:08:00+00,2015-02-01 13:13:00+00,72,W 52 St & 11 Ave,40.767272,2282,447,8 Ave & W 52 St,40.763707,-73.985162,18174,Subscriber,1974.0,1
25,NaN,-73.993929,NaN,261,2015-02-06 08:58:00+00,2015-02-06 09:02:00+00,72,W 52 St & 11 Ave,40.767272,32566,478,11 Ave & W 41 St,40.760301,-73.998842,18492,Subscriber,1971.0,1
26,NaN,-73.993929,NaN,432,2015-02-05 08:42:00+00,2015-02-05 08:49:00+00,72,W 52 St & 11 Ave,40.767272,23546,2021,W 45 St & 8 Ave,40.759291,-73.988597,21223,Subscriber,1986.0,2
27,NaN,-73.993929,NaN,1082,2015-02-03 19:06:00+00,2015-02-03 19:24:00+00,72,W 52 St & 11 Ave,40.767272,11676,463,9 Ave & W 16 St,40.742065,-74.004432,19721,Subscriber,1984.0,1
28,NaN,-73.993929,NaN,377,2015-02-05 12:55:00+00,2015-02-05 13:01:00+00,72,W 52 St & 11 Ave,40.767272,25842,500,Broadway & W 51 St,40.762288,-73.983362,16310,Subscriber,1972.0,2
29,NaN,-73.993929,NaN,871,2015-02-04 09:11:00+00,2015-02-04 09:26:00+00,72,W 52 St & 11 Ave,40.767272,14540,458,11 Ave & W 27 St,40.751396,-74.005226,20065,Subscriber,1990.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,NaN,-74.015756,NaN,493,2015-02-05 20:37:00+00,2015-02-05 20:46:00+00,3002,South End Ave & Liberty St,40.711512,30231,306,Cliff St & Fulton St,40.708235,-74.005301,17223,Subscriber,1996.0,1
46171,NaN,-74.015756,NaN,1332,2015-02-07 12:40:00+00,2015-02-07 13:02:00+00,3002,South End Ave & Liberty St,40.711512,41541,168,W 18 St & 6 Ave,40.739713,-73.994564,15495,Subscriber,1955.0,1
46172,NaN,-74.015756,NaN,316,2015-02-07 12:37:00+00,2015-02-07 12:42:00+00,3002,South End Ave & Liberty St,40.711512,41524,417,Barclay St & Church St,40.712912,-74.010202,16210,Subscriber,1967.0,2
46173,NaN,-74.015756,NaN,305,2015-02-02 10:42:00+00,2015-02-02 10:47:00+00,3002,South End Ave & Liberty St,40.711512,6901,2008,Little West St & 1 Pl,40.705693,-74.016777,17038,Subscriber,1981.0,1
46174,NaN,-74.015756,NaN,771,2015-02-02 10:16:00+00,2015-02-02 10:29:00+00,3002,South End Ave & Liberty St,40.711512,6876,329,Greenwich St & N Moore St,40.720434,-74.010206,19783,Subscriber,1991.0,1
46175,NaN,-74.015756,NaN,170,2015-02-03 20:40:00+00,2015-02-03 20:43:00+00,3002,South End Ave & Liberty St,40.711512,12171,363,West Thames St,40.708347,-74.017134,16155,Subscriber,1979.0,1
46176,NaN,-74.015756,NaN,289,2015-02-05 09:40:00+00,2015-02-05 09:45:00+00,3002,South End Ave & Liberty St,40.711512,24508,304,Broadway & Battery Pl,40.704633,-74.013617,18470,Subscriber,1975.0,1
46177,NaN,-74.015756,NaN,1776,2015-02-06 16:02:00+00,2015-02-06 16:32:00+00,3002,South End Ave & Liberty St,40.711512,35576,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,21158,Subscriber,1969.0,1
46178,NaN,-74.015756,NaN,208,2015-02-06 18:00:00+00,2015-02-06 18:04:00+00,3002,South End Ave & Liberty St,40.711512,37215,2008,Little West St & 1 Pl,40.705693,-74.016777,18718,Subscriber,1984.0,1
46179,NaN,-74.015756,NaN,293,2015-02-01 14:51:00+00,2015-02-01 14:56:00+00,3002,South End Ave & Liberty St,40.711512,3298,264,Maiden Ln & Pearl St,40.707065,-74.007319,19951,Subscriber,1990.0,1
46180,NaN,-74.015756,NaN,838,2015-02-01 18:06:00+00,2015-02-01 18:20:00+00,3002,South End Ave & Liberty St,40.711512,5261,327,Vesey Pl & River Terrace,40.715338,-74.016584,20637,Subscriber,1972.0,1
46181,NaN,-74.015756,NaN,531,2015-02-01 16:33:00+00,2015-02-01 16:42:00+00,3002,South End Ave & Liberty St,40.711512,4296,427,Bus Slip & State St,40.701907,-74.013942,19105,Subscriber,1991.0,1
46182,NaN,-74.015756,NaN,314,2015-02-06 13:20:00+00,2015-02-06 13:25:00+00,3002,South End Ave & Liberty St,40.711512,34333,304,Broadway & Battery Pl,40.704633,-74.013617,20955,Subscriber,1954.0,1
46183,NaN,-74.015756,NaN,834,2015-02-07 15:11:00+00,2015-02-07 15:25:00+00,3002,South End Ave & Liberty St,40.711512,42784,355,Bayard St & Baxter St,40.716021,-73.999744,19434,Subscriber,1959.0,1
46184,NaN,-74.015756,NaN,516,2015-02-01 16:30:00+00,2015-02-01 16:38:00+00,3002,South End Ave & Liberty St,40.711512,4269,320,Leonard St & Church St,40.717571,-74.005549,18982,Subscriber,1963.0,1
46185,NaN,-74.015756,NaN,1285,2015-02-05 16:59:00+00,2015-02-05 17:20:00+00,3002,South End Ave & Liberty St,40.711512,27637,521,8 Ave & W 31 St,40.750450,-73.994811,17061,Subscriber,1973.0,1
46186,NaN,-74.015756,NaN,925,2015-02-04 11:25:00+00,2015-02-04 11:40:00+00,3002,South End Ave & Liberty St,40.711512,15488,2000,Front St & Washington St,40.702551,-73.989402,15904,Subscriber,1988.0,1
46187,NaN,-74.015756,NaN,1218,2015-02-04 17:44:00+00,2015-02-04 18:05:00+00,3002,South End Ave & Liberty St,40.711512,18570,212,W 16 St & The High Line,40.743349,-74.006818,17632,Subscriber,1978.0,1
46188,NaN,-74.015756,NaN,1976,2015-02-02 09:21:00+00,2015-02-02 09:53:00+00,3002,South End Ave & Liberty St,40.711512,6781,494,W 26 St & 8 Ave,40.747348,-73.997236,19665,Subscriber,1959.0,1
46189,NaN,-74.015756,NaN,931,2015-02-03 21:35:00+00,2015-02-03 21:51:00+00,3002,South End Ave & Liberty St,40.711512,12373,401,Allen St & Rivington St,40.720196,-73.989978,16144,Subscriber,1973.0,2
46190,NaN,-74.015756,NaN,399,2015-02-02 09:18:00+00,2015-02-02 09:25:00+00,3002,South End Ave & Liberty St,40.711512,6777,304,Broadway & Battery Pl,40.704633,-74.013617,17448,Subscriber,1975.0,1
46191,NaN,-74.015756,NaN,771,2015-02-06 13:03:00+00,2015-02-06 13:16:00+00,3002,South End Ave & Liberty St,40.711512,34225,348,W Broadway & Spring St,40.724910,-74.001547,15977,Subscriber,1951.0,1
46192,NaN,-74.015756,NaN,943,2015-02-01 16:45:00+00,2015-02-01 17:00:00+00,3002,South End Ave & Liberty St,40.711512,4413,531,Forsyth St & Broome St,40.718939,-73.992663,20744,Subscriber,1964.0,2
46193,NaN,-74.015756,NaN,253,2015-02-04 19:36:00+00,2015-02-04 19:40:00+00,3002,South End Ave & Liberty St,40.711512,20193,2008,Little West St & 1 Pl,40.705693,-74.016777,15005,Subscriber,1972.0,2
46194,NaN,-74.015756,NaN,876,2015-02-07 16:20:00+00,2015-02-07 16:35:00+00,3002,South End Ave & Liberty St,40.711512,43446,380,W 4 St & 7 Ave S,40.734011,-74.002939,19000,Subscriber,1974.0,1
46195,NaN,-74.015756,NaN,108,2015-02-07 12:07:00+00,2015-02-07 12:09:00+00,3002,South End Ave & Liberty St,40.711512,41340,363,West Thames St,40.708347,-74.017134,18470,Subscriber,1979.0,1
46196,NaN,-74.015756,NaN,269,2015-02-05 09:27:00+00,2015-02-05 09:31:00+00,3002,South End Ave & Liberty St,40.711512,24333,195,Liberty St & Broadway,40.709056,-74.010434,16783,Subscriber,1985.0,2
46197,NaN,-74.015756,NaN,272,2015-02-03 21:53:00+00,2015-02-03 21:57:00+00,3002,South End Ave & Liberty St,40.711512,12433,2008,Little West St & 1 Pl,40.705693,-74.016777,15456,Subscriber,1991.0,2
46198,NaN,-74.015756,NaN,418,2015-02-05 09:27:00+00,2015-02-05 09:34:00+00,3002,South End Ave & Liberty St,40.711512,24329,427,Bus Slip & State St,40.701907,-74.013942,18797,Subscriber,1954.0,1
46199,NaN,-74.015756,NaN,545,2015-02-05 09:27:00+00,2015-02-05 09:36:00+00,3002,South End Ave & Liberty St,40.711512,24326,427,Bus Slip & State St,40.701907,-74.013942,20131,Subscriber,1966.0,1

In [5]:
# Sort by trip duration
q = '''
SELECT *
FROM citibike
ORDER BY tripduration
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,24408,NaN,NaN,60,2015-02-05 09:32:00+00,2015-02-05 09:33:00+00,2009,Catherine St & Monroe St,40.711174,-73.996826,2009,Catherine St & Monroe St,40.711174,-73.996826,18581,Subscriber,1983.0,1
1,7798,NaN,NaN,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,W 31 St & 7 Ave,40.749156,-73.991600,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986.0,1
2,45697,NaN,NaN,60,2015-02-07 21:40:00+00,2015-02-07 21:41:00+00,393,E 5 St & Avenue C,40.722992,-73.979955,393,E 5 St & Avenue C,40.722992,-73.979955,21524,Subscriber,1981.0,1
3,14117,NaN,NaN,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,Division St & Bowery,40.714131,-73.997047,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990.0,1
4,13482,NaN,NaN,60,2015-02-04 07:52:00+00,2015-02-04 07:53:00+00,512,W 29 St & 9 Ave,40.750073,-73.998393,512,W 29 St & 9 Ave,40.750073,-73.998393,21627,Subscriber,1960.0,2
5,38842,NaN,NaN,60,2015-02-06 20:40:00+00,2015-02-06 20:41:00+00,445,E 10 St & Avenue A,40.727408,-73.981420,445,E 10 St & Avenue A,40.727408,-73.981420,16051,Subscriber,1987.0,1
6,8284,NaN,NaN,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,Mott St & Prince St,40.723180,-73.994800,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982.0,1
7,19243,NaN,NaN,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,Laight St & Hudson St,40.721854,-74.007718,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970.0,1
8,7299,NaN,NaN,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956.0,1
9,21407,NaN,NaN,60,2015-02-04 22:38:00+00,2015-02-04 22:39:00+00,523,W 38 St & 8 Ave,40.754666,-73.991382,523,W 38 St & 8 Ave,40.754666,-73.991382,16148,Subscriber,1980.0,1
10,3110,NaN,NaN,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,E 6 St & Avenue B,40.724537,-73.981854,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985.0,1
11,11104,NaN,NaN,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,Grand St & Havemeyer St,40.712868,-73.956981,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980.0,1
12,13043,NaN,NaN,60,2015-02-04 06:54:00+00,2015-02-04 06:55:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,521,8 Ave & W 31 St,40.750450,-73.994811,14788,Subscriber,1971.0,1
13,33759,NaN,NaN,60,2015-02-06 11:38:00+00,2015-02-06 11:39:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,470,W 20 St & 8 Ave,40.743453,-74.000040,17448,Subscriber,1979.0,1
14,5715,NaN,NaN,61,2015-02-01 19:16:00+00,2015-02-01 19:17:00+00,355,Bayard St & Baxter St,40.716021,-73.999744,355,Bayard St & Baxter St,40.716021,-73.999744,15079,Subscriber,1950.0,2
15,6934,NaN,NaN,61,2015-02-02 11:22:00+00,2015-02-02 11:23:00+00,491,E 24 St & Park Ave S,40.740964,-73.986022,491,E 24 St & Park Ave S,40.740964,-73.986022,17141,Subscriber,1970.0,1
16,850,NaN,NaN,61,2015-02-01 10:26:00+00,2015-02-01 10:27:00+00,388,W 26 St & 10 Ave,40.749718,-74.002950,388,W 26 St & 10 Ave,40.749718,-74.002950,15192,Subscriber,1983.0,1
17,2570,NaN,NaN,61,2015-02-01 13:39:00+00,2015-02-01 13:40:00+00,251,Mott St & Prince St,40.723180,-73.994800,251,Mott St & Prince St,40.723180,-73.994800,20381,Subscriber,1900.0,1
18,7551,NaN,NaN,61,2015-02-02 18:51:00+00,2015-02-02 18:52:00+00,410,Suffolk St & Stanton St,40.720664,-73.985180,410,Suffolk St & Stanton St,40.720664,-73.985180,15131,Subscriber,1984.0,1
19,26912,NaN,NaN,61,2015-02-05 15:34:00+00,2015-02-05 15:35:00+00,531,Forsyth St & Broome St,40.718939,-73.992663,531,Forsyth St & Broome St,40.718939,-73.992663,16247,Subscriber,1964.0,2
20,11653,NaN,NaN,61,2015-02-03 19:01:00+00,2015-02-03 19:02:00+00,237,E 11 St & 2 Ave,40.730473,-73.986724,237,E 11 St & 2 Ave,40.730473,-73.986724,16900,Subscriber,1980.0,1
21,8962,NaN,NaN,61,2015-02-03 10:02:00+00,2015-02-03 10:03:00+00,517,Pershing Square South,40.751581,-73.977910,517,Pershing Square South,40.751581,-73.977910,19406,Subscriber,1976.0,1
22,6858,NaN,NaN,61,2015-02-02 10:05:00+00,2015-02-02 10:06:00+00,461,E 20 St & 2 Ave,40.735877,-73.982050,461,E 20 St & 2 Ave,40.735877,-73.982050,15005,Subscriber,1993.0,2
23,10622,NaN,NaN,61,2015-02-03 17:11:00+00,2015-02-03 17:12:00+00,444,Broadway & W 24 St,40.742354,-73.989151,444,Broadway & W 24 St,40.742354,-73.989151,19496,Subscriber,1986.0,1
24,30162,NaN,NaN,62,2015-02-05 20:25:00+00,2015-02-05 20:26:00+00,128,MacDougal St & Prince St,40.727103,-74.002971,128,MacDougal St & Prince St,40.727103,-74.002971,17860,Subscriber,1980.0,1
25,7135,NaN,NaN,62,2015-02-02 14:28:00+00,2015-02-02 14:29:00+00,380,W 4 St & 7 Ave S,40.734011,-74.002939,380,W 4 St & 7 Ave S,40.734011,-74.002939,16863,Subscriber,1967.0,1
26,39290,NaN,NaN,62,2015-02-06 23:06:00+00,2015-02-06 23:07:00+00,500,Broadway & W 51 St,40.762288,-73.983362,500,Broadway & W 51 St,40.762288,-73.983362,16531,Subscriber,1982.0,2
27,18151,NaN,NaN,62,2015-02-04 17:17:00+00,2015-02-04 17:18:00+00,527,E 33 St & 2 Ave,40.744023,-73.976056,527,E 33 St & 2 Ave,40.744023,-73.976056,19690,Subscriber,1983.0,1
28,36187,NaN,NaN,62,2015-02-06 16:54:00+00,2015-02-06 16:55:00+00,435,W 21 St & 6 Ave,40.741740,-73.994156,435,W 21 St & 6 Ave,40.741740,-73.994156,21649,Subscriber,1961.0,1
29,10810,NaN,NaN,62,2015-02-03 17:31:00+00,2015-02-03 17:32:00+00,511,E 14 St & Avenue B,40.729387,-73.977724,511,E 14 St & Avenue B,40.729387,-73.977724,18190,Subscriber,1994.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,40710,NaN,NaN,18559,2015-02-07 10:36:00+00,2015-02-07 15:46:00+00,512,W 29 St & 9 Ave,40.750073,-73.998393,490,8 Ave & W 33 St,40.751551,-73.993934,14988,Subscriber,1993.0,2
46171,40745,NaN,NaN,18656,2015-02-07 10:40:00+00,2015-02-07 15:51:00+00,457,Broadway & W 58 St,40.766953,-73.981693,127,Barrow St & Hudson St,40.731724,-74.006744,18646,Customer,NaN,0
46172,8673,NaN,NaN,19341,2015-02-03 09:07:00+00,2015-02-03 14:29:00+00,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,377,6 Ave & Canal St,40.722438,-74.005664,19834,Subscriber,1955.0,1
46173,13739,NaN,NaN,19629,2015-02-04 08:14:00+00,2015-02-04 13:41:00+00,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,500,Broadway & W 51 St,40.762288,-73.983362,20984,Subscriber,1971.0,1
46174,14536,NaN,NaN,20515,2015-02-04 09:11:00+00,2015-02-04 14:53:00+00,174,E 25 St & 1 Ave,40.738177,-73.977387,537,Lexington Ave & E 24 St,40.740259,-73.984092,18427,Subscriber,1996.0,1
46175,8296,NaN,NaN,21189,2015-02-03 08:11:00+00,2015-02-03 14:04:00+00,432,E 7 St & Avenue A,40.726218,-73.983799,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,18078,Subscriber,1990.0,1
46176,8247,NaN,NaN,21808,2015-02-03 08:00:00+00,2015-02-03 14:03:00+00,247,Perry St & Bleecker St,40.735354,-74.004831,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,15508,Subscriber,1968.0,1
46177,9104,NaN,NaN,21891,2015-02-03 10:44:00+00,2015-02-03 16:49:00+00,264,Maiden Ln & Pearl St,40.707065,-74.007319,304,Broadway & Battery Pl,40.704633,-74.013617,15940,Subscriber,1977.0,1
46178,12712,NaN,NaN,22207,2015-02-04 02:14:00+00,2015-02-04 08:24:00+00,303,Mercer St & Spring St,40.723627,-73.999496,294,Washington Square E,40.730494,-73.995721,18713,Subscriber,1980.0,1
46179,30910,NaN,NaN,22235,2015-02-06 01:51:00+00,2015-02-06 08:02:00+00,375,Mercer St & Bleecker St,40.726795,-73.996951,497,E 17 St & Broadway,40.737050,-73.990093,19564,Subscriber,1992.0,1
46180,21860,NaN,NaN,22236,2015-02-05 05:57:00+00,2015-02-05 12:08:00+00,519,Pershing Square North,40.751873,-73.977706,336,Sullivan St & Washington Sq,40.730477,-73.999061,18799,Subscriber,1966.0,1
46181,11772,NaN,NaN,22553,2015-02-03 19:19:00+00,2015-02-04 01:35:00+00,491,E 24 St & Park Ave S,40.740964,-73.986022,379,W 31 St & 7 Ave,40.749156,-73.991600,15797,Subscriber,1985.0,1
46182,41251,NaN,NaN,23588,2015-02-07 11:54:00+00,2015-02-07 18:27:00+00,167,E 39 St & 3 Ave,40.748901,-73.976049,527,E 33 St & 2 Ave,40.744023,-73.976056,19539,Subscriber,1978.0,2
46183,39580,NaN,NaN,26035,2015-02-07 01:49:00+00,2015-02-07 09:02:00+00,438,St Marks Pl & 1 Ave,40.727791,-73.985649,345,W 13 St & 6 Ave,40.736494,-73.997044,16631,Subscriber,1990.0,2
46184,8918,NaN,NaN,26502,2015-02-03 09:50:00+00,2015-02-03 17:12:00+00,514,12 Ave & W 40 St,40.760875,-74.002777,529,W 42 St & 8 Ave,40.757570,-73.990985,16808,Subscriber,1987.0,1
46185,10422,NaN,NaN,30216,2015-02-03 16:48:00+00,2015-02-04 01:11:00+00,402,Broadway & E 22 St,40.740343,-73.989551,356,Bialystoker Pl & Delancey St,40.716226,-73.982612,20336,Subscriber,1984.0,1
46186,12669,NaN,NaN,30260,2015-02-04 00:13:00+00,2015-02-04 08:37:00+00,505,6 Ave & W 33 St,40.749013,-73.988484,347,W Houston St & Hudson St,40.728739,-74.007488,15195,Subscriber,1967.0,1
46187,7541,NaN,NaN,31063,2015-02-02 18:47:00+00,2015-02-03 03:25:00+00,476,E 31 St & 3 Ave,40.743943,-73.979661,546,E 30 St & Park Ave S,40.744449,-73.983035,19928,Subscriber,1984.0,1
46188,8453,NaN,NaN,31142,2015-02-03 08:38:00+00,2015-02-03 17:17:00+00,312,Allen St & E Houston St,40.722055,-73.989111,519,Pershing Square North,40.751873,-73.977706,18146,Subscriber,1989.0,1
46189,6608,NaN,NaN,31251,2015-02-02 07:51:00+00,2015-02-02 16:31:00+00,291,Madison St & Montgomery St,40.713126,-73.984844,263,Elizabeth St & Hester St,40.717290,-73.996375,19651,Subscriber,1970.0,2
46190,7981,NaN,NaN,31396,2015-02-03 06:19:00+00,2015-02-03 15:03:00+00,497,E 17 St & Broadway,40.737050,-73.990093,488,W 39 St & 9 Ave,40.756458,-73.993722,16802,Subscriber,1974.0,2
46191,12444,NaN,NaN,32634,2015-02-03 22:00:00+00,2015-02-04 07:04:00+00,297,E 15 St & 3 Ave,40.734232,-73.986923,490,8 Ave & W 33 St,40.751551,-73.993934,14769,Subscriber,1982.0,1
46192,20353,NaN,NaN,33647,2015-02-04 19:52:00+00,2015-02-05 05:12:00+00,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,372,Franklin Ave & Myrtle Ave,40.694528,-73.958089,20703,Customer,NaN,0
46193,3830,NaN,NaN,35127,2015-02-01 15:47:00+00,2015-02-02 01:32:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,2009,Catherine St & Monroe St,40.711174,-73.996826,18664,Subscriber,1967.0,1
46194,78,NaN,NaN,35251,2015-02-01 00:52:00+00,2015-02-01 10:40:00+00,453,W 22 St & 8 Ave,40.744751,-73.999154,525,W 34 St & 11 Ave,40.755942,-74.002116,14691,Customer,NaN,0
46195,6670,NaN,NaN,37665,2015-02-02 08:29:00+00,2015-02-02 18:57:00+00,438,St Marks Pl & 1 Ave,40.727791,-73.985649,389,Broadway & Berry St,40.710446,-73.965251,20527,Subscriber,1977.0,1
46196,39346,NaN,NaN,41908,2015-02-06 23:31:00+00,2015-02-07 11:09:00+00,449,W 52 St & 9 Ave,40.764618,-73.987895,450,W 49 St & 8 Ave,40.762272,-73.987882,17016,Subscriber,1966.0,2
46197,7702,NaN,NaN,42784,2015-02-02 20:07:00+00,2015-02-03 08:00:00+00,195,Liberty St & Broadway,40.709056,-74.010434,387,Centre St & Chambers St,40.712733,-74.004607,18425,Subscriber,1982.0,1
46198,46083,NaN,NaN,43013,2015-02-07 23:23:00+00,2015-02-08 11:20:00+00,492,W 33 St & 7 Ave,40.750200,-73.990931,459,W 20 St & 11 Ave,40.746745,-74.007756,19209,Subscriber,1951.0,2
46199,7816,NaN,NaN,43016,2015-02-02 22:00:00+00,2015-02-03 09:57:00+00,263,Elizabeth St & Hester St,40.717290,-73.996375,250,Lafayette St & Jersey St,40.724561,-73.995653,20263,Subscriber,1955.0,1

In [6]:
# 10 shortest trips
q = '''
SELECT *
FROM citibike
ORDER BY tripduration
LIMIT 10
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,60,2015-02-04 06:54:00+00,2015-02-04 06:55:00+00,521,8 Ave & W 31 St,40.750450,13043,521,8 Ave & W 31 St,40.750450,-73.994811,14788,Subscriber,1971,1
1,NaN,-73.997047,NaN,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,Division St & Bowery,40.714131,14117,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990,1
2,NaN,-73.994800,NaN,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,Mott St & Prince St,40.723180,8284,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982,1
3,NaN,-73.956981,NaN,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,Grand St & Havemeyer St,40.712868,11104,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980,1
4,NaN,-73.981854,NaN,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,E 6 St & Avenue B,40.724537,3110,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985,1
5,NaN,-73.998393,NaN,60,2015-02-04 07:52:00+00,2015-02-04 07:53:00+00,512,W 29 St & 9 Ave,40.750073,13482,512,W 29 St & 9 Ave,40.750073,-73.998393,21627,Subscriber,1960,2
6,NaN,-73.986831,NaN,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,5 Ave & E 29 St,40.745168,7299,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956,1
7,NaN,-73.991600,NaN,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,W 31 St & 7 Ave,40.749156,7798,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986,1
8,NaN,-73.991382,NaN,60,2015-02-04 22:38:00+00,2015-02-04 22:39:00+00,523,W 38 St & 8 Ave,40.754666,21407,523,W 38 St & 8 Ave,40.754666,-73.991382,16148,Subscriber,1980,1
9,NaN,-74.007718,NaN,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,Laight St & Hudson St,40.721854,19243,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970,1

In [7]:
# 10 longest trips
q = '''
SELECT *
FROM citibike
ORDER BY tripduration DESC
LIMIT 10
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,7816,NaN,NaN,43016,2015-02-02 22:00:00+00,2015-02-03 09:57:00+00,263,Elizabeth St & Hester St,40.717290,-73.996375,250,Lafayette St & Jersey St,40.724561,-73.995653,20263,Subscriber,1955.0,1
1,46083,NaN,NaN,43013,2015-02-07 23:23:00+00,2015-02-08 11:20:00+00,492,W 33 St & 7 Ave,40.750200,-73.990931,459,W 20 St & 11 Ave,40.746745,-74.007756,19209,Subscriber,1951.0,2
2,7702,NaN,NaN,42784,2015-02-02 20:07:00+00,2015-02-03 08:00:00+00,195,Liberty St & Broadway,40.709056,-74.010434,387,Centre St & Chambers St,40.712733,-74.004607,18425,Subscriber,1982.0,1
3,39346,NaN,NaN,41908,2015-02-06 23:31:00+00,2015-02-07 11:09:00+00,449,W 52 St & 9 Ave,40.764618,-73.987895,450,W 49 St & 8 Ave,40.762272,-73.987882,17016,Subscriber,1966.0,2
4,6670,NaN,NaN,37665,2015-02-02 08:29:00+00,2015-02-02 18:57:00+00,438,St Marks Pl & 1 Ave,40.727791,-73.985649,389,Broadway & Berry St,40.710446,-73.965251,20527,Subscriber,1977.0,1
5,78,NaN,NaN,35251,2015-02-01 00:52:00+00,2015-02-01 10:40:00+00,453,W 22 St & 8 Ave,40.744751,-73.999154,525,W 34 St & 11 Ave,40.755942,-74.002116,14691,Customer,NaN,0
6,3830,NaN,NaN,35127,2015-02-01 15:47:00+00,2015-02-02 01:32:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,2009,Catherine St & Monroe St,40.711174,-73.996826,18664,Subscriber,1967.0,1
7,20353,NaN,NaN,33647,2015-02-04 19:52:00+00,2015-02-05 05:12:00+00,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,372,Franklin Ave & Myrtle Ave,40.694528,-73.958089,20703,Customer,NaN,0
8,12444,NaN,NaN,32634,2015-02-03 22:00:00+00,2015-02-04 07:04:00+00,297,E 15 St & 3 Ave,40.734232,-73.986923,490,8 Ave & W 33 St,40.751551,-73.993934,14769,Subscriber,1982.0,1
9,7981,NaN,NaN,31396,2015-02-03 06:19:00+00,2015-02-03 15:03:00+00,497,E 17 St & Broadway,40.737050,-73.990093,488,W 39 St & 9 Ave,40.756458,-73.993722,16802,Subscriber,1974.0,2

In [8]:
# 10 longest trips < 3 hours
q = '''
SELECT *
FROM citibike
WHERE tripduration < 10800
ORDER BY tripduration DESC
LIMIT 10
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-74.002638,NaN,10757,2015-02-07 12:17:00+00,2015-02-07 15:16:00+00,284,Greenwich Ave & 8 Ave,40.739017,41392,173,Broadway & W 49 St,40.760647,-73.984427,15082,Subscriber,1973,1
1,NaN,-73.998393,NaN,10660,2015-02-03 17:42:00+00,2015-02-03 20:40:00+00,512,W 29 St & 9 Ave,40.750073,10912,435,W 21 St & 6 Ave,40.741740,-73.994156,16099,Subscriber,1950,1
2,NaN,-74.008119,NaN,10174,2015-02-07 09:31:00+00,2015-02-07 12:20:00+00,405,Washington St & Gansevoort St,40.739323,40221,405,Washington St & Gansevoort St,40.739323,-74.008119,21323,Subscriber,1983,1
3,NaN,-74.002345,NaN,9969,2015-02-02 18:22:00+00,2015-02-02 21:08:00+00,386,Centre St & Worth St,40.714948,7472,264,Maiden Ln & Pearl St,40.707065,-74.007319,19921,Subscriber,1987,2
4,NaN,-73.981923,NaN,9938,2015-02-03 14:10:00+00,2015-02-03 16:55:00+00,468,Broadway & W 55 St,40.765265,9696,2023,E 55 St & Lexington Ave,40.759681,-73.970314,19070,Subscriber,1970,1
5,NaN,-73.994156,NaN,9807,2015-02-04 10:53:00+00,2015-02-04 13:36:00+00,435,W 21 St & 6 Ave,40.741740,15336,435,W 21 St & 6 Ave,40.741740,-73.994156,18088,Subscriber,1985,1
6,NaN,-73.981693,NaN,9711,2015-02-05 11:12:00+00,2015-02-05 13:54:00+00,457,Broadway & W 58 St,40.766953,25203,2021,W 45 St & 8 Ave,40.759291,-73.988597,14726,Subscriber,1962,1
7,NaN,-73.989551,NaN,9572,2015-02-04 19:09:00+00,2015-02-04 21:48:00+00,402,Broadway & E 22 St,40.740343,19897,517,Pershing Square South,40.751581,-73.977910,14691,Subscriber,1966,2
8,NaN,-73.981918,NaN,9556,2015-02-02 13:25:00+00,2015-02-02 16:05:00+00,499,Broadway & W 60 St,40.769155,7073,499,Broadway & W 60 St,40.769155,-73.981918,14802,Subscriber,1940,1
9,NaN,-73.981013,NaN,9373,2015-02-03 19:25:00+00,2015-02-03 22:01:00+00,324,DeKalb Ave & Hudson Ave,40.689888,11810,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,15018,Subscriber,1968,1

# Task 2

In [9]:
# trips started on Feb-02-2015
q = '''
SELECT *
FROM citibike
WHERE starttime >= '2015-02-02 00:00'
AND starttime < '2015-02-03 00:00'
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,6442,NaN,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,-73.993915,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
1,6443,NaN,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
2,6444,NaN,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,-74.001670,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
3,6445,NaN,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
4,6446,NaN,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,-73.990026,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
5,6447,NaN,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
6,6448,NaN,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
7,6449,NaN,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,-74.005628,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
8,6450,NaN,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
9,6451,NaN,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
10,6452,NaN,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,-73.990741,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
11,6453,NaN,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,-73.983688,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
12,6454,NaN,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,-74.001670,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
13,6455,NaN,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,-73.980166,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
14,6456,NaN,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
15,6457,NaN,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,-73.987140,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
16,6458,NaN,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
17,6459,NaN,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,-73.983390,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
18,6460,NaN,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
19,6461,NaN,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,-74.001768,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
20,6462,NaN,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,-73.979738,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
21,6463,NaN,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,-74.002939,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
22,6464,NaN,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,-73.997262,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
23,6465,NaN,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,-73.996674,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
24,6466,NaN,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,-73.987834,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
25,6467,NaN,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,-73.991930,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
26,6468,NaN,NaN,268,2015-02-02 00:29:00+00,2015-02-02 00:34:00+00,529,W 42 St & 8 Ave,40.757570,-73.990985,478,11 Ave & W 41 St,40.760301,-73.998842,20638,Subscriber,1990.0,1
27,6469,NaN,NaN,153,2015-02-02 00:29:00+00,2015-02-02 00:31:00+00,421,Clermont Ave & Park Ave,40.695734,-73.971297,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17636,Subscriber,1989.0,1
28,6470,NaN,NaN,309,2015-02-02 00:31:00+00,2015-02-02 00:36:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,494,W 26 St & 8 Ave,40.747348,-73.997236,18472,Subscriber,1982.0,1
29,6471,NaN,NaN,138,2015-02-02 00:33:00+00,2015-02-02 00:35:00+00,383,Greenwich Ave & Charles St,40.735238,-74.000271,252,MacDougal St & Washington Sq,40.732264,-73.998522,17456,Subscriber,1968.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,7871,NaN,NaN,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,Allen St & E Houston St,40.722055,-73.989111,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,7872,NaN,NaN,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,Broadway & W 29 St,40.746201,-73.988557,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,7873,NaN,NaN,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,W 56 St & 6 Ave,40.763406,-73.977225,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,7874,NaN,NaN,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,10 Ave & W 28 St,40.750664,-74.001768,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,7875,NaN,NaN,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,7876,NaN,NaN,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,Broadway & E 22 St,40.740343,-73.989551,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,7877,NaN,NaN,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,E 47 St & 2 Ave,40.753231,-73.970325,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,7878,NaN,NaN,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,Broadway & W 32 St,40.748549,-73.988084,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,7879,NaN,NaN,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,7880,NaN,NaN,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,7881,NaN,NaN,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,7882,NaN,NaN,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,7883,NaN,NaN,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,Cliff St & Fulton St,40.708235,-74.005301,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,7884,NaN,NaN,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,Rivington St & Ridge St,40.718502,-73.983299,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,7885,NaN,NaN,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,W 49 St & 8 Ave,40.762272,-73.987882,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,7886,NaN,NaN,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,Pershing Square North,40.751873,-73.977706,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,7887,NaN,NaN,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,E 30 St & Park Ave S,40.744449,-73.983035,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,7888,NaN,NaN,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,Sullivan St & Washington Sq,40.730477,-73.999061,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,7889,NaN,NaN,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,W 42 St & 8 Ave,40.757570,-73.990985,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,7890,NaN,NaN,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,Broadway & E 22 St,40.740343,-73.989551,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,7891,NaN,NaN,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,7892,NaN,NaN,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,6 Ave & W 33 St,40.749013,-73.988484,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,7893,NaN,NaN,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,9 Ave & W 22 St,40.745497,-74.001971,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,7894,NaN,NaN,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,7895,NaN,NaN,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,E 10 St & 5 Ave,40.733320,-73.995101,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,7896,NaN,NaN,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,W 44 St & 5 Ave,40.755003,-73.980144,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,7897,NaN,NaN,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,Spruce St & Nassau St,40.711464,-74.005524,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,7898,NaN,NaN,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,7899,NaN,NaN,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,W 22 St & 8 Ave,40.744751,-73.999154,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,7900,NaN,NaN,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,Broadway & E 14 St,40.734546,-73.990741,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

In [10]:
# trips started on weekend (average duration)
q = '''
SELECT AVG(tripduration)
FROM citibike
WHERE extract(DOW FROM starttime) IN (0,6)
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

          avg  Unnamed: 1
0  662.942181         NaN

In [11]:
# trips started on a weekday
q = '''
SELECT *
FROM citibike
WHERE extract(DOW FROM starttime) NOT IN (0,6)
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.976049,NaN,643,2015-02-03 14:39:00+00,2015-02-03 14:50:00+00,167,E 39 St & 3 Ave,40.748901,9806,488,W 39 St & 9 Ave,40.756458,-73.993722,17575,Subscriber,1971.0,1
1,NaN,-73.979481,NaN,1379,2015-02-04 07:07:00+00,2015-02-04 07:30:00+00,332,Cherry St,40.712199,13113,440,E 45 St & 3 Ave,40.752554,-73.972826,20313,Subscriber,1973.0,1
2,NaN,-73.993915,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,6442,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
3,NaN,-73.984267,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,6443,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
4,NaN,-74.001670,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,6444,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
5,NaN,-73.992390,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,6445,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
6,NaN,-73.990026,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,6446,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
7,NaN,-73.978951,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,6447,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
8,NaN,-74.003664,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,6448,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
9,NaN,-74.005628,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,6449,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
10,NaN,-73.994811,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,6450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
11,NaN,-73.981656,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,6451,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
12,NaN,-73.990741,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,6452,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
13,NaN,-73.983688,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,6453,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
14,NaN,-74.001670,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,6454,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
15,NaN,-73.980166,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,6455,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
16,NaN,-74.000040,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,6456,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
17,NaN,-73.987140,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,6457,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
18,NaN,-74.000040,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,6458,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
19,NaN,-73.983390,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,6459,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
20,NaN,-73.997044,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,6460,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
21,NaN,-74.001768,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,6461,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
22,NaN,-73.979738,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,6462,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
23,NaN,-74.002939,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,6463,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
24,NaN,-73.997262,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,6464,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
25,NaN,-73.996674,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,6465,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
26,NaN,-73.987834,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,6466,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
27,NaN,-73.991930,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,6467,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
28,NaN,-73.990985,NaN,268,2015-02-02 00:29:00+00,2015-02-02 00:34:00+00,529,W 42 St & 8 Ave,40.757570,6468,478,11 Ave & W 41 St,40.760301,-73.998842,20638,Subscriber,1990.0,1
29,NaN,-73.971297,NaN,153,2015-02-02 00:29:00+00,2015-02-02 00:31:00+00,421,Clermont Ave & Park Ave,40.695734,6469,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17636,Subscriber,1989.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32939,NaN,-73.986580,NaN,321,2015-02-06 23:47:00+00,2015-02-06 23:52:00+00,465,Broadway & W 41 St,40.755136,39381,492,W 33 St & 7 Ave,40.750200,-73.990931,18249,Subscriber,1957.0,1
32940,NaN,-73.991382,NaN,449,2015-02-06 23:48:00+00,2015-02-06 23:55:00+00,523,W 38 St & 8 Ave,40.754666,39382,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,19146,Subscriber,1972.0,2
32941,NaN,-74.001971,NaN,120,2015-02-06 23:48:00+00,2015-02-06 23:50:00+00,509,9 Ave & W 22 St,40.745497,39383,434,9 Ave & W 18 St,40.743174,-74.003664,15313,Subscriber,1984.0,1
32942,NaN,-73.976682,NaN,977,2015-02-06 23:49:00+00,2015-02-07 00:05:00+00,274,Lafayette Ave & Fort Greene Pl,40.686919,39384,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,18469,Subscriber,1979.0,1
32943,NaN,-73.989551,NaN,501,2015-02-06 23:49:00+00,2015-02-06 23:57:00+00,402,Broadway & E 22 St,40.740343,39385,403,E 2 St & 2 Ave,40.725029,-73.990697,18929,Subscriber,1966.0,1
32944,NaN,-73.978095,NaN,441,2015-02-06 23:50:00+00,2015-02-06 23:58:00+00,545,E 23 St & 1 Ave,40.736502,39386,402,Broadway & E 22 St,40.740343,-73.989551,19009,Subscriber,1987.0,1
32945,NaN,-73.984738,NaN,388,2015-02-06 23:50:00+00,2015-02-06 23:57:00+00,325,E 19 St & 3 Ave,40.736245,39387,438,St Marks Pl & 1 Ave,40.727791,-73.985649,17102,Subscriber,1984.0,1
32946,NaN,-73.990765,NaN,607,2015-02-06 23:51:00+00,2015-02-07 00:01:00+00,293,Lafayette St & E 8 St,40.730287,39388,266,Avenue D & E 8 St,40.723684,-73.975748,18686,Subscriber,1972.0,2
32947,NaN,-73.989551,NaN,284,2015-02-06 23:51:00+00,2015-02-06 23:55:00+00,402,Broadway & E 22 St,40.740343,39389,472,E 32 St & Park Ave,40.745712,-73.981948,15377,Subscriber,1989.0,1
32948,NaN,-74.000271,NaN,271,2015-02-06 23:51:00+00,2015-02-06 23:56:00+00,383,Greenwich Ave & Charles St,40.735238,39390,435,W 21 St & 6 Ave,40.741740,-73.994156,17844,Subscriber,1984.0,1
32949,NaN,-73.991908,NaN,572,2015-02-06 23:52:00+00,2015-02-07 00:01:00+00,361,Allen St & Hester St,40.716059,39391,438,St Marks Pl & 1 Ave,40.727791,-73.985649,21040,Subscriber,1987.0,1
32950,NaN,-73.987520,NaN,498,2015-02-06 23:53:00+00,2015-02-07 00:01:00+00,503,E 20 St & Park Ave,40.738274,39392,380,W 4 St & 7 Ave S,40.734011,-74.002939,19480,Subscriber,1981.0,1
32951,NaN,-73.981013,NaN,425,2015-02-06 23:53:00+00,2015-02-07 00:00:00+00,324,DeKalb Ave & Hudson Ave,40.689888,39393,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,21130,Subscriber,1978.0,1
32952,NaN,-73.992390,NaN,267,2015-02-06 23:53:00+00,2015-02-06 23:58:00+00,496,E 16 St & 5 Ave,40.737262,39394,435,W 21 St & 6 Ave,40.741740,-73.994156,16934,Subscriber,1983.0,1
32953,NaN,-73.980144,NaN,165,2015-02-06 23:53:00+00,2015-02-06 23:56:00+00,484,W 44 St & 5 Ave,40.755003,39395,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20745,Subscriber,1968.0,1
32954,NaN,-73.967597,NaN,751,2015-02-06 23:54:00+00,2015-02-07 00:06:00+00,464,E 56 St & 3 Ave,40.759345,39396,507,E 25 St & 2 Ave,40.739126,-73.979738,16811,Subscriber,1969.0,1
32955,NaN,-73.983688,NaN,747,2015-02-06 23:54:00+00,2015-02-07 00:07:00+00,301,E 2 St & Avenue B,40.722174,39397,476,E 31 St & 3 Ave,40.743943,-73.979661,21259,Subscriber,1980.0,1
32956,NaN,-73.989780,NaN,511,2015-02-06 23:54:00+00,2015-02-07 00:03:00+00,439,E 4 St & 2 Ave,40.726281,39398,375,Mercer St & Bleecker St,40.726795,-73.996951,15618,Subscriber,1993.0,1
32957,NaN,-73.990093,NaN,489,2015-02-06 23:54:00+00,2015-02-07 00:02:00+00,497,E 17 St & Broadway,40.737050,39399,486,Broadway & W 29 St,40.746201,-73.988557,17370,Subscriber,1959.0,1
32958,NaN,-73.981656,NaN,1183,2015-02-06 23:55:00+00,2015-02-07 00:14:00+00,504,1 Ave & E 15 St,40.732219,39400,295,Pike St & E Broadway,40.714067,-73.992939,19430,Subscriber,1984.0,1
32959,NaN,-73.980420,NaN,649,2015-02-06 23:55:00+00,2015-02-07 00:06:00+00,510,W 51 St & 6 Ave,40.760660,39401,512,W 29 St & 9 Ave,40.750073,-73.998393,18303,Subscriber,1986.0,1
32960,NaN,-73.998004,NaN,377,2015-02-06 23:55:00+00,2015-02-07 00:01:00+00,254,W 11 St & 6 Ave,40.735324,39402,453,W 22 St & 8 Ave,40.744751,-73.999154,20360,Subscriber,1990.0,1
32961,NaN,-74.000040,NaN,485,2015-02-06 23:56:00+00,2015-02-07 00:04:00+00,470,W 20 St & 8 Ave,40.743453,39403,491,E 24 St & Park Ave S,40.740964,-73.986022,21564,Subscriber,1983.0,1
32962,NaN,-73.999318,NaN,298,2015-02-06 23:56:00+00,2015-02-07 00:01:00+00,482,W 15 St & 7 Ave,40.739355,39404,368,Carmine St & 6 Ave,40.730386,-74.002150,21575,Subscriber,1983.0,1
32963,NaN,-73.982050,NaN,648,2015-02-06 23:57:00+00,2015-02-07 00:07:00+00,461,E 20 St & 2 Ave,40.735877,39405,346,Bank St & Hudson St,40.736529,-74.006180,21014,Subscriber,1983.0,1
32964,NaN,-73.998522,NaN,1261,2015-02-06 23:58:00+00,2015-02-07 00:19:00+00,252,MacDougal St & Washington Sq,40.732264,39406,450,W 49 St & 8 Ave,40.762272,-73.987882,17797,Subscriber,1989.0,2
32965,NaN,-73.981013,NaN,331,2015-02-06 23:58:00+00,2015-02-07 00:04:00+00,324,DeKalb Ave & Hudson Ave,40.689888,39407,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,16975,Subscriber,1984.0,1
32966,NaN,-73.997044,NaN,629,2015-02-06 23:59:00+00,2015-02-07 00:10:00+00,345,W 13 St & 6 Ave,40.736494,39408,236,St Marks Pl & 2 Ave,40.728419,-73.987140,19820,Subscriber,1982.0,1
32967,NaN,-73.996375,NaN,492,2015-02-06 23:59:00+00,2015-02-07 00:07:00+00,263,Elizabeth St & Hester St,40.717290,39409,502,Henry St & Grand St,40.714215,-73.981346,19487,Subscriber,1966.0,1
32968,NaN,-73.989978,NaN,329,2015-02-06 23:59:00+00,2015-02-07 00:04:00+00,401,Allen St & Rivington St,40.720196,39410,301,E 2 St & Avenue B,40.722174,-73.983688,15426,Subscriber,1987.0,1

# Task 3

In [12]:
# start station locations
q = '''
SELECT start_station_latitude, start_station_longitude
FROM citibike
GROUP BY start_station_latitude, start_station_longitude
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

     start_station_latitude  start_station_longitude
0                 40.686919               -73.976682
1                 40.753202               -73.977987
2                 40.715422               -74.011220
3                 40.745497               -74.001971
4                 40.744751               -73.999154
5                 40.742065               -74.004432
6                 40.740964               -73.986022
7                 40.763406               -73.977225
8                 40.716059               -73.991908
9                 40.714948               -74.002345
10                40.703799               -74.008387
11                40.708531               -73.964090
12                40.727434               -73.993790
13                40.762288               -73.983362
14                40.727103               -74.002971
15                40.760660               -73.980420
16                40.685396               -73.974315
17                40.714979               -74.013012
18                40.693317               -73.953820
19                40.688515               -73.964763
20                40.720828               -73.977932
21                40.718710               -74.009001
22                40.690893               -73.996123
23                40.737262               -73.992390
24                40.735238               -74.000271
25                40.683826               -73.976323
26                40.767272               -73.993929
27                40.719392               -74.002472
28                40.750200               -73.990931
29                40.686768               -73.959282
..                      ...                      ...
297               40.689269               -73.989129
298               40.693631               -73.962236
299               40.689888               -73.981013
300               40.770513               -73.988038
301               40.751396               -74.005226
302               40.738177               -73.977387
303               40.721854               -74.007718
304               40.697666               -73.984764
305               40.684568               -73.958811
306               40.686832               -73.979677
307               40.746647               -73.993915
308               40.684157               -73.969223
309               40.715816               -73.994224
310               40.720196               -73.989978
311               40.732241               -74.000264
312               40.735354               -74.004831
313               40.720874               -73.980858
314               40.763441               -73.982681
315               40.750664               -74.001768
316               40.759291               -73.988597
317               40.730386               -74.002150
318               40.683178               -73.965964
319               40.700379               -73.995481
320               40.751873               -73.977706
321               40.764618               -73.987895
322               40.748238               -73.978311
323               40.726218               -73.983799
324               40.746920               -74.004519
325               40.719105               -73.999733
326               40.717227               -73.988021

[327 rows x 2 columns]

In [13]:
# number of trips per station
q = '''
SELECT COUNT(*)
FROM citibike
GROUP BY start_station_id, start_station_latitude, start_station_longitude
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

     count  Unnamed: 1
0      156         NaN
1       78         NaN
2       46         NaN
3      203         NaN
4       27         NaN
5      327         NaN
6      151         NaN
7       37         NaN
8      279         NaN
9      100         NaN
10     111         NaN
11     145         NaN
12     168         NaN
13     133         NaN
14      85         NaN
15     110         NaN
16      78         NaN
17      69         NaN
18     145         NaN
19     151         NaN
20     455         NaN
21      99         NaN
22       7         NaN
23     125         NaN
24      69         NaN
25     207         NaN
26     238         NaN
27     250         NaN
28     137         NaN
29      55         NaN
..     ...         ...
297     88         NaN
298    259         NaN
299    159         NaN
300    156         NaN
301    111         NaN
302    186         NaN
303     50         NaN
304    120         NaN
305     71         NaN
306    142         NaN
307    123         NaN
308     89         NaN
309     34         NaN
310    107         NaN
311    292         NaN
312     41         NaN
313     27         NaN
314    172         NaN
315    257         NaN
316     28         NaN
317    289         NaN
318    218         NaN
319    132         NaN
320    100         NaN
321     63         NaN
322    177         NaN
323    222         NaN
324    157         NaN
325    173         NaN
326     65         NaN

[327 rows x 2 columns]

In [14]:
# stations within 500m of Times Square
q = '''
SELECT
    start_station_id,
    CDB_TransformToWebmercator(CDB_LatLng(
        start_station_latitude,
        start_station_longitude
        )
    ) as the_geom_webmercator,
    MIN(cartodb_id) as cartodb_id,
    COUNT(tripduration) as numtrips
FROM citibike
WHERE
     ST_DWithin(CDB_LatLng(
         start_station_latitude,
         start_station_longitude
     )::geography,
     CDB_LatLng(40.7577,-73.9857)::geography, 500)
GROUP BY
      start_station_id,
      start_station_latitude,
      start_station_longitude'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,start_station_id,the_geom_webmercator,cartodb_id,numtrips
0,477,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,507
1,2021,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,141
2,465,0101000020110F000004AF971C1D6B5FC17A48F3C1A8FB...,54,251
3,493,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,141
4,524,0101000020110F0000F22A632FBE6A5FC1363A28CFADFB...,1115,112
5,529,0101000020110F00003F9300B2976B5FC1B8B88F3102FC...,783,221
6,173,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,213

# Task 4

In [15]:
# station with the longest average trip duration during weekends
# and within 500m of Times Square.
q = '''
SELECT
    start_station_id,
    CDB_TransformToWebmercator(CDB_LatLng(
      start_station_latitude,
      start_station_longitude)
    ) as the_geom_webmercator,
    MIN(cartodb_id) as cartodb_id, AVG(tripduration) as avg_duration
FROM citibike
WHERE
     ST_DWithin(
         CDB_LatLng(
              start_station_latitude,
         start_station_longitude
)::geography, CDB_LatLng(40.7577,-73.9857)::geography, 500)
AND
extract(DOW FROM starttime) IN (0,6)
GROUP BY
      start_station_id,
      start_station_latitude,
      start_station_longitude
ORDER BY avg_duration DESC LIMIT 1
'''
pd.read_csv(io(queryCartoDB(q)), sep=',')

,start_station_id,the_geom_webmercator,cartodb_id,avg_duration
0,173,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,1010.104167

## ASH Score 100. Extra Credit 100